version: "3.3"
services:
  frontend:
    container_name: frontEndContainer
    build:
      context: ./Integrated-FrontEnd/IntegratedNw2FrontEnd
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - '80:80'
    # networks: 
    #   - external
    depends_on:
      - backend

  frontendv2:
    container_name: frontEndContainerV2
    build:
      context: ./Integrated-FrontEnd/IntegratedNw2FrontEnd
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - '3000:80'
    # networks: 
    #   - external
    depends_on:
      - backend

  backend:
    container_name: backEndContainer
    build:
      context: ./Integrated-BackEnd
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - '8080:8080'
    # networks: 
    #   - internal
    depends_on:
      - dbserver     
  dbserver:
    container_name: dataContainer
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: 'kradanItBangMod'
      MYSQL_ROOT_PASSWORD: 'nw2'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysqldb:/var/lib/mysql
      - mysqlconfig:/etc/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: "exit 0"
    # networks: 
    #   internal:
    #     driver: bridge

  # reverse_proxy:
  #   image: nginx:latest
  #   container_name: reverse_proxy
  #   ports:
  #     - 80:80
  #   volumes: 
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - dbserver
  #     - backend

volumes:
  mysqldb:
  mysqlconfig:
