version: "3.3"
services:
  dbserver:
    container_name: dataContainer
    build:
      context: ./Integrated-DataBase
      dockerfile: Dockerfile
    volumes:
      - mysqldb:/var/lib/mysql
      - mysqlconfig:/etc/mysql
    ports:
      - '3306:3306'
    networks: 
      - DB-network


  backend:
    container_name: backEndContainer
    build:
      context: ./Integrated-BackEnd
      dockerfile: Dockerfile
    networks: 
      - DB-network
      - FE-network

  frontendv2:
    container_name: frontEndContainerV2
    build:
      context: ./Integrated-FrontEnd/IntegratedNw2FrontEnd
      dockerfile: Dockerfile
    networks: 
      - FE-network

  reverse_proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - FE-network

volumes:
  mysqldb:
  mysqlconfig:

networks:
  DB-network:
  FE-network:

