services:
  frontend:
    container_name: frontEndContainer
    build:
      context: ./Integrated-FrontEnd/IntegratedNw2FrontEnd
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5173:80'
    # networks: 
    #   - internal
    depends_on:
      - backend
  backend:
    container_name: backEndContainer
    build:
      context: ./Integrated-BackEnd
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbserver:3306/kradanItBangMod
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nw2
      SPRING_JPA.HIBERNATE: update
    # networks: 
    #   - internal
    depends_on:
      - dbserver     
 
  dbserver:
    container_name: dataContainer
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: 'kradanItBangMod'
      MYSQL_ROOT_PASSWORD: 'nw2'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - mysqldb:/var/lib/mysql
      - mysqlconfig:/etc/mysql
    healthcheck:
      test: "exit 0"
    # networks: 
    #   - internal

volumes:
  mysqldb:
  mysqlconfig:

# networks: 
