version: "3.3"
services:
  dbserver:
    container_name: dataContainer
        build:
      context: ./Integrated-DataBase
      dockerfile: Dockerfile
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: 'kradanItBangMod'
      MYSQL_ROOT_PASSWORD: 'nw2'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysqldb:/var/lib/mysql
      - mysqlconfig:/etc/mysql
    ports:
      - '3306:3306'
    networks: 
      - DB-network


  backend:
    container_name: backEndContainer
    build:
      context: ./Integrated-BackEnd
      dockerfile: Dockerfile
    networks: 
      - DB-network
      - FE-network
    depends_on:
      - dbserver 

  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - FE-network
    depends_on:
      - dbserver
      - backend

  # frontend:
  #   container_name: frontEndContainer
  #   build:
  #     context: ./Integrated-FrontEnd/IntegratedNw2FrontEnd
  #     dockerfile: Dockerfile
  #   restart: always
  #   networks: 
  #     - FE-network
  #   depends_on:
      # - dbserver
      # - backend
      # - reverse_proxy

  frontendv2:
    container_name: frontEndContainerV2
    build:
      context: ./Integrated-FrontEnd/IntegratedNw2FrontEnd
      dockerfile: Dockerfile
    networks: 
      - FE-network
    depends_on:
    #   - dbserver
      - backend
    #   - reverse_proxy

volumes:
  mysqldb:
  mysqlconfig:

networks:
  DB-network:
  FE-network:
